[window]
decorations = "full"
opacity = 1.0
blur=false
dynamic_title = true
dynamic_padding=true
padding={ x = 16, y = 4 }
startup_mode="maximized"
option_as_alt = "Both"
title="Terminal"

[font]
size = 14.0

[terminal.shell]
program = "/bin/zsh"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[colors.primary]
background = "#1c1b19"
foreground = "#d8d0c0"

[colors.cursor]
text = "#1c1b19"
cursor = "#e08060"

[colors.selection]
text = "#d8d0c0"
background = "#3e3c38"

[colors.normal]
black   = "#1c1b19"
red     = "#e08060"
green   = "#8a9868"
yellow  = "#c8b468"
blue    = "#7890a0"
magenta = "#b07878"
cyan    = "#80a090"
white   = "#d8d0c0"

[colors.bright]
black   = "#1c1b19"
red     = "#e08060"
green   = "#8a9868"
yellow  = "#c8b468"
blue    = "#7890a0"
magenta = "#b07878"
cyan    = "#80a090"
white   = "#d8d0c0"

[cursor]
blink_interval = 750
unfocused_hollow = true

[cursor.style]
shape = "Block"
blinking = "on"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[bell]
animation = "EaseOutExpo"
duration = 0
color = "#e08060"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\n"
