# Fuzzel — centered lower, Alacritty colors
# bg #121012 · accent #d33355 · fg #c8c8d6

font=JetBrainsMono Nerd Font:size=13
dpi-aware=no

terminal=alacritty -e
prompt="󰍉  "
placeholder=search…
icon-theme=Papirus-Dark
icons-enabled=yes
image-size-ratio=0.6

fields=filename,name,generic
match-mode=fzf
sort-result=yes
match-counter=yes

# true center
anchor=center
lines=10
width=40
horizontal-pad=22
vertical-pad=14
inner-pad=10
line-height=26

layer=overlay
exit-on-keyboard-focus-loss=yes

[colors]
background=121012ff
text=c8c8d6ff
prompt=d33355ff
placeholder=6e6e80ff
input=c8c8d6ff
match=e8456aff
selection=5a2436ff
selection-text=c8c8d6ff
selection-match=e8456aff
counter=6e6e80ff
border=d33355cc

[border]
width=2
radius=0

[dmenu]
exit-immediately-if-empty=yes
